# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/btCalibrate.ui'
#
# Created: Tue Jul 12 14:03:47 2016
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_btCalibrate(object):
    def setupUi(self, btCalibrate):
        btCalibrate.setObjectName(_fromUtf8("btCalibrate"))
        btCalibrate.resize(900, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(btCalibrate.sizePolicy().hasHeightForWidth())
        btCalibrate.setSizePolicy(sizePolicy)
        btCalibrate.setMinimumSize(QtCore.QSize(900, 600))
        btCalibrate.setMaximumSize(QtCore.QSize(900, 600))
        self.loadImageButton = QtGui.QPushButton(btCalibrate)
        self.loadImageButton.setGeometry(QtCore.QRect(810, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loadImageButton.setFont(font)
        self.loadImageButton.setObjectName(_fromUtf8("loadImageButton"))
        self.imageView = QtGui.QGraphicsView(btCalibrate)
        self.imageView.setGeometry(QtCore.QRect(180, 110, 711, 481))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageView.sizePolicy().hasHeightForWidth())
        self.imageView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.imageView.setFont(font)
        self.imageView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.imageView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.imageView.setObjectName(_fromUtf8("imageView"))
        self.noImageLabel = QtGui.QLabel(btCalibrate)
        self.noImageLabel.setGeometry(QtCore.QRect(480, 360, 131, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.noImageLabel.setPalette(palette)
        self.noImageLabel.setObjectName(_fromUtf8("noImageLabel"))
        self.loadBeaconsButton = QtGui.QPushButton(btCalibrate)
        self.loadBeaconsButton.setGeometry(QtCore.QRect(810, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loadBeaconsButton.setFont(font)
        self.loadBeaconsButton.setObjectName(_fromUtf8("loadBeaconsButton"))
        self.clearBeaconsButton = QtGui.QPushButton(btCalibrate)
        self.clearBeaconsButton.setGeometry(QtCore.QRect(850, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.clearBeaconsButton.setFont(font)
        self.clearBeaconsButton.setObjectName(_fromUtf8("clearBeaconsButton"))
        self.resetImageButton = QtGui.QPushButton(btCalibrate)
        self.resetImageButton.setGeometry(QtCore.QRect(850, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.resetImageButton.setFont(font)
        self.resetImageButton.setObjectName(_fromUtf8("resetImageButton"))
        self.label = QtGui.QLabel(btCalibrate)
        self.label.setGeometry(QtCore.QRect(730, 13, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(btCalibrate)
        self.label_2.setGeometry(QtCore.QRect(730, 32, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pointSelectBox = QtGui.QGroupBox(btCalibrate)
        self.pointSelectBox.setGeometry(QtCore.QRect(180, 10, 81, 101))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pointSelectBox.setFont(font)
        self.pointSelectBox.setTitle(_fromUtf8(""))
        self.pointSelectBox.setFlat(False)
        self.pointSelectBox.setCheckable(False)
        self.pointSelectBox.setObjectName(_fromUtf8("pointSelectBox"))
        self.point1 = QtGui.QRadioButton(self.pointSelectBox)
        self.point1.setGeometry(QtCore.QRect(0, 0, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.point1.setFont(font)
        self.point1.setObjectName(_fromUtf8("point1"))
        self.point2 = QtGui.QRadioButton(self.pointSelectBox)
        self.point2.setGeometry(QtCore.QRect(0, 20, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.point2.setFont(font)
        self.point2.setObjectName(_fromUtf8("point2"))
        self.origin = QtGui.QRadioButton(self.pointSelectBox)
        self.origin.setGeometry(QtCore.QRect(0, 40, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.origin.setFont(font)
        self.origin.setObjectName(_fromUtf8("origin"))
        self.positive = QtGui.QRadioButton(self.pointSelectBox)
        self.positive.setGeometry(QtCore.QRect(0, 60, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.positive.setFont(font)
        self.positive.setObjectName(_fromUtf8("positive"))
        self.edit = QtGui.QRadioButton(self.pointSelectBox)
        self.edit.setGeometry(QtCore.QRect(0, 80, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.edit.setFont(font)
        self.edit.setObjectName(_fromUtf8("edit"))
        self.labelPoint1 = QtGui.QLabel(btCalibrate)
        self.labelPoint1.setGeometry(QtCore.QRect(270, 29, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelPoint1.setFont(font)
        self.labelPoint1.setObjectName(_fromUtf8("labelPoint1"))
        self.labelPoint2 = QtGui.QLabel(btCalibrate)
        self.labelPoint2.setGeometry(QtCore.QRect(270, 49, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelPoint2.setFont(font)
        self.labelPoint2.setObjectName(_fromUtf8("labelPoint2"))
        self.calibrateButton = QtGui.QPushButton(btCalibrate)
        self.calibrateButton.setGeometry(QtCore.QRect(450, 71, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.calibrateButton.setFont(font)
        self.calibrateButton.setObjectName(_fromUtf8("calibrateButton"))
        self.meterBox = QtGui.QDoubleSpinBox(btCalibrate)
        self.meterBox.setGeometry(QtCore.QRect(390, 70, 62, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.meterBox.setFont(font)
        self.meterBox.setObjectName(_fromUtf8("meterBox"))
        self.mergeButton = QtGui.QPushButton(btCalibrate)
        self.mergeButton.setGeometry(QtCore.QRect(70, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mergeButton.setFont(font)
        self.mergeButton.setObjectName(_fromUtf8("mergeButton"))
        self.resetDataButton = QtGui.QPushButton(btCalibrate)
        self.resetDataButton.setGeometry(QtCore.QRect(130, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.resetDataButton.setFont(font)
        self.resetDataButton.setObjectName(_fromUtf8("resetDataButton"))
        self.beaconsAvailable = QtGui.QListWidget(btCalibrate)
        self.beaconsAvailable.setGeometry(QtCore.QRect(10, 370, 161, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        self.beaconsAvailable.setFont(font)
        self.beaconsAvailable.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.beaconsAvailable.setObjectName(_fromUtf8("beaconsAvailable"))
        self.filesAvailable = QtGui.QListWidget(btCalibrate)
        self.filesAvailable.setGeometry(QtCore.QRect(10, 30, 161, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        self.filesAvailable.setFont(font)
        self.filesAvailable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.filesAvailable.setObjectName(_fromUtf8("filesAvailable"))
        self.selectNoneButton = QtGui.QPushButton(btCalibrate)
        self.selectNoneButton.setGeometry(QtCore.QRect(50, 350, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectNoneButton.setFont(font)
        self.selectNoneButton.setObjectName(_fromUtf8("selectNoneButton"))
        self.selectAllButton = QtGui.QPushButton(btCalibrate)
        self.selectAllButton.setGeometry(QtCore.QRect(10, 350, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectAllButton.setFont(font)
        self.selectAllButton.setObjectName(_fromUtf8("selectAllButton"))
        self.pointsAvailable = QtGui.QListWidget(btCalibrate)
        self.pointsAvailable.setGeometry(QtCore.QRect(10, 200, 161, 141))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pointsAvailable.setFont(font)
        self.pointsAvailable.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.pointsAvailable.setObjectName(_fromUtf8("pointsAvailable"))
        self.readDataButton = QtGui.QPushButton(btCalibrate)
        self.readDataButton.setGeometry(QtCore.QRect(10, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.readDataButton.setFont(font)
        self.readDataButton.setObjectName(_fromUtf8("readDataButton"))
        self.labelOrigin = QtGui.QLabel(btCalibrate)
        self.labelOrigin.setGeometry(QtCore.QRect(270, 69, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelOrigin.setFont(font)
        self.labelOrigin.setObjectName(_fromUtf8("labelOrigin"))
        self.labelPositive = QtGui.QLabel(btCalibrate)
        self.labelPositive.setGeometry(QtCore.QRect(270, 89, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelPositive.setFont(font)
        self.labelPositive.setObjectName(_fromUtf8("labelPositive"))
        self.labelParity = QtGui.QLabel(btCalibrate)
        self.labelParity.setGeometry(QtCore.QRect(270, 10, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelParity.setFont(font)
        self.labelParity.setObjectName(_fromUtf8("labelParity"))
        self.saveParametersButton = QtGui.QPushButton(btCalibrate)
        self.saveParametersButton.setGeometry(QtCore.QRect(850, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.saveParametersButton.setFont(font)
        self.saveParametersButton.setObjectName(_fromUtf8("saveParametersButton"))
        self.loadParametersButton = QtGui.QPushButton(btCalibrate)
        self.loadParametersButton.setGeometry(QtCore.QRect(810, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loadParametersButton.setFont(font)
        self.loadParametersButton.setObjectName(_fromUtf8("loadParametersButton"))
        self.label_3 = QtGui.QLabel(btCalibrate)
        self.label_3.setGeometry(QtCore.QRect(730, 53, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.exportButton = QtGui.QPushButton(btCalibrate)
        self.exportButton.setGeometry(QtCore.QRect(830, 90, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.exportButton.setFont(font)
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.label_4 = QtGui.QLabel(btCalibrate)
        self.label_4.setGeometry(QtCore.QRect(690, 72, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.loadConversionButton = QtGui.QPushButton(btCalibrate)
        self.loadConversionButton.setGeometry(QtCore.QRect(810, 70, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loadConversionButton.setFont(font)
        self.loadConversionButton.setObjectName(_fromUtf8("loadConversionButton"))
        self.saveConversionButton = QtGui.QPushButton(btCalibrate)
        self.saveConversionButton.setGeometry(QtCore.QRect(850, 70, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.saveConversionButton.setFont(font)
        self.saveConversionButton.setObjectName(_fromUtf8("saveConversionButton"))
        self.setLimitsButton = QtGui.QPushButton(btCalibrate)
        self.setLimitsButton.setGeometry(QtCore.QRect(390, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.setLimitsButton.setFont(font)
        self.setLimitsButton.setObjectName(_fromUtf8("setLimitsButton"))
        self.labelLimits = QtGui.QLabel(btCalibrate)
        self.labelLimits.setGeometry(QtCore.QRect(462, 92, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelLimits.setFont(font)
        self.labelLimits.setObjectName(_fromUtf8("labelLimits"))
        self.exportBox = QtGui.QComboBox(btCalibrate)
        self.exportBox.setGeometry(QtCore.QRect(680, 90, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.exportBox.setFont(font)
        self.exportBox.setObjectName(_fromUtf8("exportBox"))
        self.clearConversionButton = QtGui.QPushButton(btCalibrate)
        self.clearConversionButton.setGeometry(QtCore.QRect(770, 70, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.clearConversionButton.setFont(font)
        self.clearConversionButton.setObjectName(_fromUtf8("clearConversionButton"))

        self.retranslateUi(btCalibrate)
        QtCore.QMetaObject.connectSlotsByName(btCalibrate)

    def retranslateUi(self, btCalibrate):
        btCalibrate.setWindowTitle(_translate("btCalibrate", "Map Calibrator", None))
        self.loadImageButton.setText(_translate("btCalibrate", "Load", None))
        self.noImageLabel.setText(_translate("btCalibrate", "No Image Loaded", None))
        self.loadBeaconsButton.setText(_translate("btCalibrate", "Load", None))
        self.clearBeaconsButton.setText(_translate("btCalibrate", "Clear", None))
        self.resetImageButton.setText(_translate("btCalibrate", "Clear", None))
        self.label.setText(_translate("btCalibrate", "Map Image: ", None))
        self.label_2.setText(_translate("btCalibrate", "Beacons: ", None))
        self.point1.setText(_translate("btCalibrate", "Point 1", None))
        self.point2.setText(_translate("btCalibrate", "Point 2", None))
        self.origin.setText(_translate("btCalibrate", "Origin", None))
        self.positive.setText(_translate("btCalibrate", "Positive", None))
        self.edit.setText(_translate("btCalibrate", "Edit", None))
        self.labelPoint1.setText(_translate("btCalibrate", "Point 1:", None))
        self.labelPoint2.setText(_translate("btCalibrate", "Point 2:", None))
        self.calibrateButton.setText(_translate("btCalibrate", "Calibrate", None))
        self.mergeButton.setText(_translate("btCalibrate", "Merge All", None))
        self.resetDataButton.setText(_translate("btCalibrate", "Reset", None))
        self.selectNoneButton.setText(_translate("btCalibrate", "None", None))
        self.selectAllButton.setText(_translate("btCalibrate", "All", None))
        self.readDataButton.setText(_translate("btCalibrate", "Add Files", None))
        self.labelOrigin.setText(_translate("btCalibrate", "Origin:", None))
        self.labelPositive.setText(_translate("btCalibrate", "Positive:", None))
        self.labelParity.setText(_translate("btCalibrate", "Parity:", None))
        self.saveParametersButton.setText(_translate("btCalibrate", "Save", None))
        self.loadParametersButton.setText(_translate("btCalibrate", "Load", None))
        self.label_3.setText(_translate("btCalibrate", "Parameters: ", None))
        self.exportButton.setText(_translate("btCalibrate", "Export", None))
        self.label_4.setText(_translate("btCalibrate", "Conversion: ", None))
        self.loadConversionButton.setText(_translate("btCalibrate", "Load", None))
        self.saveConversionButton.setText(_translate("btCalibrate", "Save", None))
        self.setLimitsButton.setText(_translate("btCalibrate", "Set Limits", None))
        self.labelLimits.setText(_translate("btCalibrate", "Limits:", None))
        self.clearConversionButton.setText(_translate("btCalibrate", "Clear", None))

