# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/btInterpolate.ui'
#
# Created: Sat Mar  5 21:43:02 2016
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_btInterpolate(object):
    def setupUi(self, btInterpolate):
        btInterpolate.setObjectName(_fromUtf8("btInterpolate"))
        btInterpolate.resize(1200, 520)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(btInterpolate.sizePolicy().hasHeightForWidth())
        btInterpolate.setSizePolicy(sizePolicy)
        btInterpolate.setMinimumSize(QtCore.QSize(1200, 520))
        btInterpolate.setMaximumSize(QtCore.QSize(1200, 520))
        self.loadImageButton = QtGui.QPushButton(btInterpolate)
        self.loadImageButton.setGeometry(QtCore.QRect(280, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loadImageButton.setFont(font)
        self.loadImageButton.setObjectName(_fromUtf8("loadImageButton"))
        self.imageView = QtGui.QGraphicsView(btInterpolate)
        self.imageView.setGeometry(QtCore.QRect(180, 30, 711, 481))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageView.sizePolicy().hasHeightForWidth())
        self.imageView.setSizePolicy(sizePolicy)
        self.imageView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.imageView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.imageView.setObjectName(_fromUtf8("imageView"))
        self.noImageLabel = QtGui.QLabel(btInterpolate)
        self.noImageLabel.setGeometry(QtCore.QRect(490, 280, 121, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.noImageLabel.setPalette(palette)
        self.noImageLabel.setObjectName(_fromUtf8("noImageLabel"))
        self.resetImageButton = QtGui.QPushButton(btInterpolate)
        self.resetImageButton.setGeometry(QtCore.QRect(320, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.resetImageButton.setFont(font)
        self.resetImageButton.setObjectName(_fromUtf8("resetImageButton"))
        self.label = QtGui.QLabel(btInterpolate)
        self.label.setGeometry(QtCore.QRect(200, 12, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.resetDataButton = QtGui.QPushButton(btInterpolate)
        self.resetDataButton.setGeometry(QtCore.QRect(70, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.resetDataButton.setFont(font)
        self.resetDataButton.setObjectName(_fromUtf8("resetDataButton"))
        self.beaconsAvailable = QtGui.QListWidget(btInterpolate)
        self.beaconsAvailable.setGeometry(QtCore.QRect(10, 280, 161, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        self.beaconsAvailable.setFont(font)
        self.beaconsAvailable.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.beaconsAvailable.setObjectName(_fromUtf8("beaconsAvailable"))
        self.pointsAvailable = QtGui.QListWidget(btInterpolate)
        self.pointsAvailable.setGeometry(QtCore.QRect(10, 60, 161, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pointsAvailable.setFont(font)
        self.pointsAvailable.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.pointsAvailable.setObjectName(_fromUtf8("pointsAvailable"))
        self.readDataButton = QtGui.QPushButton(btInterpolate)
        self.readDataButton.setGeometry(QtCore.QRect(10, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.readDataButton.setFont(font)
        self.readDataButton.setObjectName(_fromUtf8("readDataButton"))
        self.loadParametersButton = QtGui.QPushButton(btInterpolate)
        self.loadParametersButton.setGeometry(QtCore.QRect(460, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loadParametersButton.setFont(font)
        self.loadParametersButton.setObjectName(_fromUtf8("loadParametersButton"))
        self.label_3 = QtGui.QLabel(btInterpolate)
        self.label_3.setGeometry(QtCore.QRect(380, 12, 81, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.dataFile = QtGui.QLabel(btInterpolate)
        self.dataFile.setGeometry(QtCore.QRect(10, 40, 161, 16))
        self.dataFile.setObjectName(_fromUtf8("dataFile"))
        self.histView1 = GraphicsLayoutWidget(btInterpolate)
        self.histView1.setGeometry(QtCore.QRect(900, 100, 291, 131))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.histView1.setBackgroundBrush(brush)
        self.histView1.setObjectName(_fromUtf8("histView1"))
        self.histView0 = GraphicsLayoutWidget(btInterpolate)
        self.histView0.setGeometry(QtCore.QRect(900, 240, 291, 131))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.histView0.setBackgroundBrush(brush)
        self.histView0.setObjectName(_fromUtf8("histView0"))
        self.histView2 = GraphicsLayoutWidget(btInterpolate)
        self.histView2.setGeometry(QtCore.QRect(900, 380, 291, 131))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.histView2.setBackgroundBrush(brush)
        self.histView2.setObjectName(_fromUtf8("histView2"))
        self.sliderT = QtGui.QSlider(btInterpolate)
        self.sliderT.setGeometry(QtCore.QRect(1080, 20, 41, 16))
        self.sliderT.setMaximum(100)
        self.sliderT.setSingleStep(1)
        self.sliderT.setOrientation(QtCore.Qt.Horizontal)
        self.sliderT.setObjectName(_fromUtf8("sliderT"))
        self.sliderBeta = QtGui.QSlider(btInterpolate)
        self.sliderBeta.setGeometry(QtCore.QRect(1080, 40, 41, 16))
        self.sliderBeta.setMaximum(100)
        self.sliderBeta.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBeta.setObjectName(_fromUtf8("sliderBeta"))
        self.t = QtGui.QLabel(btInterpolate)
        self.t.setGeometry(QtCore.QRect(1130, 20, 61, 16))
        self.t.setObjectName(_fromUtf8("t"))
        self.beta = QtGui.QLabel(btInterpolate)
        self.beta.setGeometry(QtCore.QRect(1130, 40, 61, 16))
        self.beta.setObjectName(_fromUtf8("beta"))
        self.sliderR = QtGui.QSlider(btInterpolate)
        self.sliderR.setGeometry(QtCore.QRect(920, 40, 41, 16))
        self.sliderR.setMaximum(100)
        self.sliderR.setOrientation(QtCore.Qt.Horizontal)
        self.sliderR.setObjectName(_fromUtf8("sliderR"))
        self.theta = QtGui.QLabel(btInterpolate)
        self.theta.setGeometry(QtCore.QRect(970, 20, 61, 16))
        self.theta.setObjectName(_fromUtf8("theta"))
        self.sliderTheta = QtGui.QSlider(btInterpolate)
        self.sliderTheta.setGeometry(QtCore.QRect(920, 20, 41, 16))
        self.sliderTheta.setMaximum(100)
        self.sliderTheta.setSingleStep(1)
        self.sliderTheta.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTheta.setObjectName(_fromUtf8("sliderTheta"))
        self.r = QtGui.QLabel(btInterpolate)
        self.r.setGeometry(QtCore.QRect(970, 40, 61, 16))
        self.r.setObjectName(_fromUtf8("r"))
        self.thetaBox = QtGui.QCheckBox(btInterpolate)
        self.thetaBox.setGeometry(QtCore.QRect(900, 20, 16, 16))
        self.thetaBox.setText(_fromUtf8(""))
        self.thetaBox.setObjectName(_fromUtf8("thetaBox"))
        self.loadBetavsPairsButton = QtGui.QPushButton(btInterpolate)
        self.loadBetavsPairsButton.setGeometry(QtCore.QRect(900, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loadBetavsPairsButton.setFont(font)
        self.loadBetavsPairsButton.setObjectName(_fromUtf8("loadBetavsPairsButton"))
        self.mousePoint = QtGui.QLabel(btInterpolate)
        self.mousePoint.setGeometry(QtCore.QRect(10, 410, 161, 20))
        self.mousePoint.setText(_fromUtf8(""))
        self.mousePoint.setObjectName(_fromUtf8("mousePoint"))

        self.retranslateUi(btInterpolate)
        QtCore.QMetaObject.connectSlotsByName(btInterpolate)

    def retranslateUi(self, btInterpolate):
        btInterpolate.setWindowTitle(_translate("btInterpolate", "Interpolation Tool", None))
        self.loadImageButton.setText(_translate("btInterpolate", "Load", None))
        self.noImageLabel.setText(_translate("btInterpolate", "No Image Loaded", None))
        self.resetImageButton.setText(_translate("btInterpolate", "Clear", None))
        self.label.setText(_translate("btInterpolate", "Map Image:", None))
        self.resetDataButton.setText(_translate("btInterpolate", "Reset", None))
        self.readDataButton.setText(_translate("btInterpolate", "Add Files", None))
        self.loadParametersButton.setText(_translate("btInterpolate", "Load", None))
        self.label_3.setText(_translate("btInterpolate", "Parameters:", None))
        self.dataFile.setText(_translate("btInterpolate", "File:", None))
        self.t.setText(_translate("btInterpolate", "t:", None))
        self.beta.setText(_translate("btInterpolate", "β:", None))
        self.theta.setText(_translate("btInterpolate", "θ:", None))
        self.r.setText(_translate("btInterpolate", "r:", None))
        self.loadBetavsPairsButton.setText(_translate("btInterpolate", "Read β-pairs", None))

from pyqtgraph import GraphicsLayoutWidget
