# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/btLivePlot.ui'
#
# Created: Fri Mar 25 15:50:32 2016
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BeaconLivePlot(object):
    def setupUi(self, BeaconLivePlot):
        BeaconLivePlot.setObjectName(_fromUtf8("BeaconLivePlot"))
        BeaconLivePlot.resize(891, 624)
        BeaconLivePlot.setMinimumSize(QtCore.QSize(400, 300))
        BeaconLivePlot.setMaximumSize(QtCore.QSize(5000, 5000))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 143, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        BeaconLivePlot.setPalette(palette)
        self.plotView = GraphicsLayoutWidget(BeaconLivePlot)
        self.plotView.setGeometry(QtCore.QRect(450, 60, 431, 371))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.plotView.setBackgroundBrush(brush)
        self.plotView.setObjectName(_fromUtf8("plotView"))
        self.btPlotList = QtGui.QListWidget(BeaconLivePlot)
        self.btPlotList.setGeometry(QtCore.QRect(10, 60, 431, 251))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 143, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.btPlotList.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        self.btPlotList.setFont(font)
        self.btPlotList.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.btPlotList.setObjectName(_fromUtf8("btPlotList"))
        self.timeLabel = QtGui.QLabel(BeaconLivePlot)
        self.timeLabel.setGeometry(QtCore.QRect(260, 15, 91, 16))
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.labelTime = QtGui.QLabel(BeaconLivePlot)
        self.labelTime.setGeometry(QtCore.QRect(370, 13, 51, 20))
        self.labelTime.setText(_fromUtf8(""))
        self.labelTime.setObjectName(_fromUtf8("labelTime"))
        self.label = QtGui.QLabel(BeaconLivePlot)
        self.label.setGeometry(QtCore.QRect(10, 40, 231, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.selectAllButton = QtGui.QPushButton(BeaconLivePlot)
        self.selectAllButton.setGeometry(QtCore.QRect(50, 310, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectAllButton.setFont(font)
        self.selectAllButton.setObjectName(_fromUtf8("selectAllButton"))
        self.selectNoneButton = QtGui.QPushButton(BeaconLivePlot)
        self.selectNoneButton.setGeometry(QtCore.QRect(10, 310, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectNoneButton.setFont(font)
        self.selectNoneButton.setObjectName(_fromUtf8("selectNoneButton"))
        self.histView = GraphicsLayoutWidget(BeaconLivePlot)
        self.histView.setGeometry(QtCore.QRect(10, 360, 431, 231))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.histView.setBackgroundBrush(brush)
        self.histView.setObjectName(_fromUtf8("histView"))
        self.selectInstructionLabel_2 = QtGui.QLabel(BeaconLivePlot)
        self.selectInstructionLabel_2.setGeometry(QtCore.QRect(10, 340, 121, 21))
        self.selectInstructionLabel_2.setWordWrap(True)
        self.selectInstructionLabel_2.setObjectName(_fromUtf8("selectInstructionLabel_2"))
        self.histResetButton = QtGui.QPushButton(BeaconLivePlot)
        self.histResetButton.setGeometry(QtCore.QRect(10, 590, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histResetButton.setFont(font)
        self.histResetButton.setObjectName(_fromUtf8("histResetButton"))
        self.collectDataShow = QtGui.QListWidget(BeaconLivePlot)
        self.collectDataShow.setGeometry(QtCore.QRect(450, 490, 171, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        font.setPointSize(6)
        self.collectDataShow.setFont(font)
        self.collectDataShow.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.collectDataShow.setObjectName(_fromUtf8("collectDataShow"))
        self.plotResetButton = QtGui.QPushButton(BeaconLivePlot)
        self.plotResetButton.setGeometry(QtCore.QRect(450, 430, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plotResetButton.setFont(font)
        self.plotResetButton.setObjectName(_fromUtf8("plotResetButton"))
        self.deviceSelectBox = QtGui.QComboBox(BeaconLivePlot)
        self.deviceSelectBox.setGeometry(QtCore.QRect(10, 10, 231, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 143, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.deviceSelectBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        font.setPointSize(8)
        self.deviceSelectBox.setFont(font)
        self.deviceSelectBox.setObjectName(_fromUtf8("deviceSelectBox"))
        self.selectResetButton = QtGui.QPushButton(BeaconLivePlot)
        self.selectResetButton.setGeometry(QtCore.QRect(380, 310, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectResetButton.setFont(font)
        self.selectResetButton.setObjectName(_fromUtf8("selectResetButton"))
        self.dps = QtGui.QLabel(BeaconLivePlot)
        self.dps.setGeometry(QtCore.QRect(450, 470, 161, 16))
        self.dps.setObjectName(_fromUtf8("dps"))

        self.retranslateUi(BeaconLivePlot)
        QtCore.QMetaObject.connectSlotsByName(BeaconLivePlot)

    def retranslateUi(self, BeaconLivePlot):
        BeaconLivePlot.setWindowTitle(_translate("BeaconLivePlot", "Live Beacon Data Plot", None))
        self.timeLabel.setText(_translate("BeaconLivePlot", "Time Elapsed:", None))
        self.label.setText(_translate("BeaconLivePlot", "Select a MAC address to visualize.", None))
        self.selectAllButton.setText(_translate("BeaconLivePlot", "All", None))
        self.selectNoneButton.setText(_translate("BeaconLivePlot", "None", None))
        self.selectInstructionLabel_2.setText(_translate("BeaconLivePlot", "Histogram viewer.", None))
        self.histResetButton.setText(_translate("BeaconLivePlot", "Reset", None))
        self.plotResetButton.setText(_translate("BeaconLivePlot", "Reset", None))
        self.selectResetButton.setText(_translate("BeaconLivePlot", "Refresh", None))
        self.dps.setText(_translate("BeaconLivePlot", "DPS:", None))

from pyqtgraph import GraphicsLayoutWidget
