# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/btLocator.ui'
#
# Created: Wed Mar 30 21:24:49 2016
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BeaconLoc(object):
    def setupUi(self, BeaconLoc):
        BeaconLoc.setObjectName(_fromUtf8("BeaconLoc"))
        BeaconLoc.resize(1366, 748)
        BeaconLoc.setMinimumSize(QtCore.QSize(400, 300))
        BeaconLoc.setMaximumSize(QtCore.QSize(5000, 5000))
        self.plotView = GraphicsLayoutWidget(BeaconLoc)
        self.plotView.setGeometry(QtCore.QRect(10, 40, 431, 371))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.plotView.setBackgroundBrush(brush)
        self.plotView.setObjectName(_fromUtf8("plotView"))
        self.btPlotList = QtGui.QListWidget(BeaconLoc)
        self.btPlotList.setGeometry(QtCore.QRect(450, 30, 241, 181))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        font.setPointSize(8)
        self.btPlotList.setFont(font)
        self.btPlotList.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.btPlotList.setObjectName(_fromUtf8("btPlotList"))
        self.loadImageButton = QtGui.QPushButton(BeaconLoc)
        self.loadImageButton.setGeometry(QtCore.QRect(810, 680, 101, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loadImageButton.setFont(font)
        self.loadImageButton.setObjectName(_fromUtf8("loadImageButton"))
        self.placeBeaconButton = QtGui.QPushButton(BeaconLoc)
        self.placeBeaconButton.setGeometry(QtCore.QRect(610, 470, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.placeBeaconButton.setFont(font)
        self.placeBeaconButton.setObjectName(_fromUtf8("placeBeaconButton"))
        self.timeLabel = QtGui.QLabel(BeaconLoc)
        self.timeLabel.setGeometry(QtCore.QRect(260, 15, 91, 16))
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.labelTime = QtGui.QLabel(BeaconLoc)
        self.labelTime.setGeometry(QtCore.QRect(370, 13, 51, 20))
        self.labelTime.setText(_fromUtf8(""))
        self.labelTime.setObjectName(_fromUtf8("labelTime"))
        self.imageView = QtGui.QGraphicsView(BeaconLoc)
        self.imageView.setGeometry(QtCore.QRect(700, 10, 651, 661))
        self.imageView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.imageView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.imageView.setObjectName(_fromUtf8("imageView"))
        self.dataCollectButton = QtGui.QPushButton(BeaconLoc)
        self.dataCollectButton.setGeometry(QtCore.QRect(630, 270, 61, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dataCollectButton.setFont(font)
        self.dataCollectButton.setObjectName(_fromUtf8("dataCollectButton"))
        self.selectBeaconList = QtGui.QListWidget(BeaconLoc)
        self.selectBeaconList.setGeometry(QtCore.QRect(450, 470, 131, 231))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        font.setPointSize(8)
        self.selectBeaconList.setFont(font)
        self.selectBeaconList.setAlternatingRowColors(False)
        self.selectBeaconList.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.selectBeaconList.setObjectName(_fromUtf8("selectBeaconList"))
        self.noImageLabel = QtGui.QLabel(BeaconLoc)
        self.noImageLabel.setGeometry(QtCore.QRect(970, 370, 121, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.noImageLabel.setPalette(palette)
        self.noImageLabel.setObjectName(_fromUtf8("noImageLabel"))
        self.instructionLabel = QtGui.QLabel(BeaconLoc)
        self.instructionLabel.setGeometry(QtCore.QRect(580, 470, 121, 51))
        self.instructionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.instructionLabel.setWordWrap(True)
        self.instructionLabel.setObjectName(_fromUtf8("instructionLabel"))
        self.beaconOkButton = QtGui.QPushButton(BeaconLoc)
        self.beaconOkButton.setGeometry(QtCore.QRect(590, 541, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.beaconOkButton.setFont(font)
        self.beaconOkButton.setObjectName(_fromUtf8("beaconOkButton"))
        self.beaconWarningLabel = QtGui.QLabel(BeaconLoc)
        self.beaconWarningLabel.setGeometry(QtCore.QRect(580, 520, 121, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.beaconWarningLabel.setPalette(palette)
        self.beaconWarningLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.beaconWarningLabel.setWordWrap(True)
        self.beaconWarningLabel.setOpenExternalLinks(False)
        self.beaconWarningLabel.setObjectName(_fromUtf8("beaconWarningLabel"))
        self.labelSelected = QtGui.QLabel(BeaconLoc)
        self.labelSelected.setGeometry(QtCore.QRect(580, 610, 121, 31))
        self.labelSelected.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelSelected.setWordWrap(True)
        self.labelSelected.setObjectName(_fromUtf8("labelSelected"))
        self.pointNotPut = QtGui.QLabel(BeaconLoc)
        self.pointNotPut.setGeometry(QtCore.QRect(590, 650, 101, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.pointNotPut.setPalette(palette)
        self.pointNotPut.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.pointNotPut.setWordWrap(True)
        self.pointNotPut.setObjectName(_fromUtf8("pointNotPut"))
        self.beaconCancelButton = QtGui.QPushButton(BeaconLoc)
        self.beaconCancelButton.setGeometry(QtCore.QRect(610, 570, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.beaconCancelButton.setFont(font)
        self.beaconCancelButton.setObjectName(_fromUtf8("beaconCancelButton"))
        self.saveBeaconsButton = QtGui.QPushButton(BeaconLoc)
        self.saveBeaconsButton.setGeometry(QtCore.QRect(920, 680, 101, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.saveBeaconsButton.setFont(font)
        self.saveBeaconsButton.setObjectName(_fromUtf8("saveBeaconsButton"))
        self.labelCollect = QtGui.QLabel(BeaconLoc)
        self.labelCollect.setGeometry(QtCore.QRect(450, 320, 171, 16))
        self.labelCollect.setObjectName(_fromUtf8("labelCollect"))
        self.dataStartButton = QtGui.QPushButton(BeaconLoc)
        self.dataStartButton.setGeometry(QtCore.QRect(630, 360, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dataStartButton.setFont(font)
        self.dataStartButton.setObjectName(_fromUtf8("dataStartButton"))
        self.dataCancelButton = QtGui.QPushButton(BeaconLoc)
        self.dataCancelButton.setGeometry(QtCore.QRect(630, 380, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dataCancelButton.setFont(font)
        self.dataCancelButton.setObjectName(_fromUtf8("dataCancelButton"))
        self.selectInstructionLabel = QtGui.QLabel(BeaconLoc)
        self.selectInstructionLabel.setGeometry(QtCore.QRect(450, 450, 231, 21))
        self.selectInstructionLabel.setWordWrap(True)
        self.selectInstructionLabel.setObjectName(_fromUtf8("selectInstructionLabel"))
        self.line = QtGui.QFrame(BeaconLoc)
        self.line.setGeometry(QtCore.QRect(450, 430, 241, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(BeaconLoc)
        self.label.setGeometry(QtCore.QRect(450, 10, 231, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.line_2 = QtGui.QFrame(BeaconLoc)
        self.line_2.setGeometry(QtCore.QRect(450, 230, 241, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_2 = QtGui.QLabel(BeaconLoc)
        self.label_2.setGeometry(QtCore.QRect(450, 250, 241, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.loggedPointsButton = QtGui.QPushButton(BeaconLoc)
        self.loggedPointsButton.setGeometry(QtCore.QRect(1250, 680, 101, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loggedPointsButton.setFont(font)
        self.loggedPointsButton.setObjectName(_fromUtf8("loggedPointsButton"))
        self.beaconRemoveButton = QtGui.QPushButton(BeaconLoc)
        self.beaconRemoveButton.setGeometry(QtCore.QRect(640, 541, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.beaconRemoveButton.setFont(font)
        self.beaconRemoveButton.setObjectName(_fromUtf8("beaconRemoveButton"))
        self.selectAllButton = QtGui.QPushButton(BeaconLoc)
        self.selectAllButton.setGeometry(QtCore.QRect(490, 210, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectAllButton.setFont(font)
        self.selectAllButton.setObjectName(_fromUtf8("selectAllButton"))
        self.selectNoneButton = QtGui.QPushButton(BeaconLoc)
        self.selectNoneButton.setGeometry(QtCore.QRect(450, 210, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectNoneButton.setFont(font)
        self.selectNoneButton.setObjectName(_fromUtf8("selectNoneButton"))
        self.histView = GraphicsLayoutWidget(BeaconLoc)
        self.histView.setGeometry(QtCore.QRect(10, 470, 431, 231))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.histView.setBackgroundBrush(brush)
        self.histView.setObjectName(_fromUtf8("histView"))
        self.line_3 = QtGui.QFrame(BeaconLoc)
        self.line_3.setGeometry(QtCore.QRect(10, 430, 431, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.selectInstructionLabel_2 = QtGui.QLabel(BeaconLoc)
        self.selectInstructionLabel_2.setGeometry(QtCore.QRect(10, 450, 121, 21))
        self.selectInstructionLabel_2.setWordWrap(True)
        self.selectInstructionLabel_2.setObjectName(_fromUtf8("selectInstructionLabel_2"))
        self.histResetButton = QtGui.QPushButton(BeaconLoc)
        self.histResetButton.setGeometry(QtCore.QRect(10, 700, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histResetButton.setFont(font)
        self.histResetButton.setObjectName(_fromUtf8("histResetButton"))
        self.loadBeaconsButton = QtGui.QPushButton(BeaconLoc)
        self.loadBeaconsButton.setGeometry(QtCore.QRect(1030, 680, 101, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loadBeaconsButton.setFont(font)
        self.loadBeaconsButton.setObjectName(_fromUtf8("loadBeaconsButton"))
        self.saveBeaconsAsButton = QtGui.QPushButton(BeaconLoc)
        self.saveBeaconsAsButton.setGeometry(QtCore.QRect(920, 710, 101, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.saveBeaconsAsButton.setFont(font)
        self.saveBeaconsAsButton.setObjectName(_fromUtf8("saveBeaconsAsButton"))
        self.clearBeaconsButton = QtGui.QPushButton(BeaconLoc)
        self.clearBeaconsButton.setGeometry(QtCore.QRect(1030, 710, 101, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.clearBeaconsButton.setFont(font)
        self.clearBeaconsButton.setObjectName(_fromUtf8("clearBeaconsButton"))
        self.resetImageButton = QtGui.QPushButton(BeaconLoc)
        self.resetImageButton.setGeometry(QtCore.QRect(810, 710, 101, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.resetImageButton.setFont(font)
        self.resetImageButton.setObjectName(_fromUtf8("resetImageButton"))
        self.clearPointsButton = QtGui.QPushButton(BeaconLoc)
        self.clearPointsButton.setGeometry(QtCore.QRect(1250, 710, 101, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.clearPointsButton.setFont(font)
        self.clearPointsButton.setObjectName(_fromUtf8("clearPointsButton"))
        self.durationSpinBox = QtGui.QSpinBox(BeaconLoc)
        self.durationSpinBox.setGeometry(QtCore.QRect(630, 340, 61, 21))
        self.durationSpinBox.setMaximum(1440)
        self.durationSpinBox.setSingleStep(1)
        self.durationSpinBox.setProperty("value", 10)
        self.durationSpinBox.setObjectName(_fromUtf8("durationSpinBox"))
        self.durationCheckBox = QtGui.QCheckBox(BeaconLoc)
        self.durationCheckBox.setGeometry(QtCore.QRect(620, 320, 81, 19))
        self.durationCheckBox.setObjectName(_fromUtf8("durationCheckBox"))
        self.dataOpenFileButton = QtGui.QPushButton(BeaconLoc)
        self.dataOpenFileButton.setGeometry(QtCore.QRect(450, 270, 61, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dataOpenFileButton.setFont(font)
        self.dataOpenFileButton.setObjectName(_fromUtf8("dataOpenFileButton"))
        self.dataOpenedFileLabel = QtGui.QLabel(BeaconLoc)
        self.dataOpenedFileLabel.setGeometry(QtCore.QRect(450, 300, 171, 16))
        self.dataOpenedFileLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dataOpenedFileLabel.setObjectName(_fromUtf8("dataOpenedFileLabel"))
        self.dataResetFileButton = QtGui.QPushButton(BeaconLoc)
        self.dataResetFileButton.setGeometry(QtCore.QRect(520, 270, 61, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dataResetFileButton.setFont(font)
        self.dataResetFileButton.setObjectName(_fromUtf8("dataResetFileButton"))
        self.durationLeftTime = QtGui.QLabel(BeaconLoc)
        self.durationLeftTime.setGeometry(QtCore.QRect(630, 410, 61, 31))
        self.durationLeftTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.durationLeftTime.setWordWrap(True)
        self.durationLeftTime.setObjectName(_fromUtf8("durationLeftTime"))
        self.collectDataShow = QtGui.QListWidget(BeaconLoc)
        self.collectDataShow.setGeometry(QtCore.QRect(450, 360, 171, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        font.setPointSize(6)
        self.collectDataShow.setFont(font)
        self.collectDataShow.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.collectDataShow.setObjectName(_fromUtf8("collectDataShow"))
        self.plotResetButton = QtGui.QPushButton(BeaconLoc)
        self.plotResetButton.setGeometry(QtCore.QRect(10, 410, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plotResetButton.setFont(font)
        self.plotResetButton.setObjectName(_fromUtf8("plotResetButton"))
        self.deviceSelectBox = QtGui.QComboBox(BeaconLoc)
        self.deviceSelectBox.setGeometry(QtCore.QRect(10, 10, 231, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        font.setPointSize(8)
        self.deviceSelectBox.setFont(font)
        self.deviceSelectBox.setObjectName(_fromUtf8("deviceSelectBox"))
        self.selectResetButton = QtGui.QPushButton(BeaconLoc)
        self.selectResetButton.setGeometry(QtCore.QRect(650, 210, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectResetButton.setFont(font)
        self.selectResetButton.setObjectName(_fromUtf8("selectResetButton"))
        self.dps = QtGui.QLabel(BeaconLoc)
        self.dps.setGeometry(QtCore.QRect(450, 340, 161, 16))
        self.dps.setObjectName(_fromUtf8("dps"))

        self.retranslateUi(BeaconLoc)
        QtCore.QMetaObject.connectSlotsByName(BeaconLoc)

    def retranslateUi(self, BeaconLoc):
        BeaconLoc.setWindowTitle(_translate("BeaconLoc", "Beacon Locator", None))
        self.loadImageButton.setText(_translate("BeaconLoc", "Load Image", None))
        self.placeBeaconButton.setText(_translate("BeaconLoc", "Place\n"
"Beacon", None))
        self.timeLabel.setText(_translate("BeaconLoc", "Time Elapsed:", None))
        self.dataCollectButton.setText(_translate("BeaconLoc", "Collect", None))
        self.noImageLabel.setText(_translate("BeaconLoc", "No Image Loaded", None))
        self.instructionLabel.setText(_translate("BeaconLoc", "Place the selected beacon and press OK", None))
        self.beaconOkButton.setText(_translate("BeaconLoc", "OK", None))
        self.beaconWarningLabel.setText(_translate("BeaconLoc", "No Image loaded!", None))
        self.labelSelected.setText(_translate("BeaconLoc", "Beacon MAC", None))
        self.pointNotPut.setText(_translate("BeaconLoc", "Put a point first!", None))
        self.beaconCancelButton.setText(_translate("BeaconLoc", "Cancel", None))
        self.saveBeaconsButton.setText(_translate("BeaconLoc", "Save Beacons", None))
        self.labelCollect.setText(_translate("BeaconLoc", "Collecting at", None))
        self.dataStartButton.setText(_translate("BeaconLoc", "Start", None))
        self.dataCancelButton.setText(_translate("BeaconLoc", "Cancel", None))
        self.selectInstructionLabel.setText(_translate("BeaconLoc", "Select a MAC address to place.", None))
        self.label.setText(_translate("BeaconLoc", "Select a MAC address.", None))
        self.label_2.setText(_translate("BeaconLoc", "Push \"Collect Data\" to start collecting.", None))
        self.loggedPointsButton.setText(_translate("BeaconLoc", "Logged Points", None))
        self.beaconRemoveButton.setText(_translate("BeaconLoc", "Remove", None))
        self.selectAllButton.setText(_translate("BeaconLoc", "All", None))
        self.selectNoneButton.setText(_translate("BeaconLoc", "None", None))
        self.selectInstructionLabel_2.setText(_translate("BeaconLoc", "Histogram viewer.", None))
        self.histResetButton.setText(_translate("BeaconLoc", "Reset", None))
        self.loadBeaconsButton.setText(_translate("BeaconLoc", "Load Beacons", None))
        self.saveBeaconsAsButton.setText(_translate("BeaconLoc", "Save As", None))
        self.clearBeaconsButton.setText(_translate("BeaconLoc", "Clear Beacons", None))
        self.resetImageButton.setText(_translate("BeaconLoc", "Reset Image", None))
        self.clearPointsButton.setText(_translate("BeaconLoc", "Clear Points", None))
        self.durationCheckBox.setText(_translate("BeaconLoc", "Duration", None))
        self.dataOpenFileButton.setText(_translate("BeaconLoc", "Open", None))
        self.dataOpenedFileLabel.setText(_translate("BeaconLoc", "Open File", None))
        self.dataResetFileButton.setText(_translate("BeaconLoc", "Reset", None))
        self.durationLeftTime.setText(_translate("BeaconLoc", "Min. left:", None))
        self.plotResetButton.setText(_translate("BeaconLoc", "Reset", None))
        self.selectResetButton.setText(_translate("BeaconLoc", "Reset", None))
        self.dps.setText(_translate("BeaconLoc", "DPS:", None))

from pyqtgraph import GraphicsLayoutWidget
