# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/btViewer.ui'
#
# Created: Fri Jun 10 18:57:56 2016
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BeaconView(object):
    def setupUi(self, BeaconView):
        BeaconView.setObjectName(_fromUtf8("BeaconView"))
        BeaconView.resize(1361, 748)
        BeaconView.setMinimumSize(QtCore.QSize(400, 300))
        BeaconView.setMaximumSize(QtCore.QSize(5000, 5000))
        self.plotTimeView = GraphicsLayoutWidget(BeaconView)
        self.plotTimeView.setGeometry(QtCore.QRect(10, 570, 1341, 161))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.plotTimeView.setBackgroundBrush(brush)
        self.plotTimeView.setObjectName(_fromUtf8("plotTimeView"))
        self.pointsAvailable = QtGui.QListWidget(BeaconView)
        self.pointsAvailable.setGeometry(QtCore.QRect(10, 200, 91, 141))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pointsAvailable.setFont(font)
        self.pointsAvailable.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.pointsAvailable.setObjectName(_fromUtf8("pointsAvailable"))
        self.loadImageButton = QtGui.QPushButton(BeaconView)
        self.loadImageButton.setGeometry(QtCore.QRect(810, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loadImageButton.setFont(font)
        self.loadImageButton.setObjectName(_fromUtf8("loadImageButton"))
        self.imageView = QtGui.QGraphicsView(BeaconView)
        self.imageView.setGeometry(QtCore.QRect(810, 40, 541, 511))
        self.imageView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.imageView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.imageView.setObjectName(_fromUtf8("imageView"))
        self.noImageLabel = QtGui.QLabel(BeaconView)
        self.noImageLabel.setGeometry(QtCore.QRect(1030, 300, 111, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.noImageLabel.setPalette(palette)
        self.noImageLabel.setObjectName(_fromUtf8("noImageLabel"))
        self.readDataButton = QtGui.QPushButton(BeaconView)
        self.readDataButton.setGeometry(QtCore.QRect(10, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.readDataButton.setFont(font)
        self.readDataButton.setObjectName(_fromUtf8("readDataButton"))
        self.selectAllButton = QtGui.QPushButton(BeaconView)
        self.selectAllButton.setGeometry(QtCore.QRect(10, 350, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectAllButton.setFont(font)
        self.selectAllButton.setObjectName(_fromUtf8("selectAllButton"))
        self.selectNoneButton = QtGui.QPushButton(BeaconView)
        self.selectNoneButton.setGeometry(QtCore.QRect(50, 350, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectNoneButton.setFont(font)
        self.selectNoneButton.setObjectName(_fromUtf8("selectNoneButton"))
        self.loadBeaconsButton = QtGui.QPushButton(BeaconView)
        self.loadBeaconsButton.setGeometry(QtCore.QRect(1030, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loadBeaconsButton.setFont(font)
        self.loadBeaconsButton.setObjectName(_fromUtf8("loadBeaconsButton"))
        self.clearBeaconsButton = QtGui.QPushButton(BeaconView)
        self.clearBeaconsButton.setGeometry(QtCore.QRect(1070, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.clearBeaconsButton.setFont(font)
        self.clearBeaconsButton.setObjectName(_fromUtf8("clearBeaconsButton"))
        self.resetImageButton = QtGui.QPushButton(BeaconView)
        self.resetImageButton.setGeometry(QtCore.QRect(850, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.resetImageButton.setFont(font)
        self.resetImageButton.setObjectName(_fromUtf8("resetImageButton"))
        self.clearPointsButton = QtGui.QPushButton(BeaconView)
        self.clearPointsButton.setGeometry(QtCore.QRect(1310, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.clearPointsButton.setFont(font)
        self.clearPointsButton.setObjectName(_fromUtf8("clearPointsButton"))
        self.plotResetButton = QtGui.QPushButton(BeaconView)
        self.plotResetButton.setGeometry(QtCore.QRect(60, 550, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plotResetButton.setFont(font)
        self.plotResetButton.setObjectName(_fromUtf8("plotResetButton"))
        self.resetDataButton = QtGui.QPushButton(BeaconView)
        self.resetDataButton.setGeometry(QtCore.QRect(130, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.resetDataButton.setFont(font)
        self.resetDataButton.setObjectName(_fromUtf8("resetDataButton"))
        self.beaconsAvailable = QtGui.QListWidget(BeaconView)
        self.beaconsAvailable.setGeometry(QtCore.QRect(10, 370, 161, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        self.beaconsAvailable.setFont(font)
        self.beaconsAvailable.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.beaconsAvailable.setObjectName(_fromUtf8("beaconsAvailable"))
        self.timeSeriesButton = QtGui.QPushButton(BeaconView)
        self.timeSeriesButton.setGeometry(QtCore.QRect(10, 550, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.timeSeriesButton.setFont(font)
        self.timeSeriesButton.setObjectName(_fromUtf8("timeSeriesButton"))
        self.putPointsButton = QtGui.QPushButton(BeaconView)
        self.putPointsButton.setGeometry(QtCore.QRect(1270, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.putPointsButton.setFont(font)
        self.putPointsButton.setObjectName(_fromUtf8("putPointsButton"))
        self.label = QtGui.QLabel(BeaconView)
        self.label.setGeometry(QtCore.QRect(810, 4, 41, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(BeaconView)
        self.label_2.setGeometry(QtCore.QRect(1030, 4, 57, 14))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(BeaconView)
        self.label_3.setGeometry(QtCore.QRect(1270, 4, 81, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.filesAvailable = QtGui.QListWidget(BeaconView)
        self.filesAvailable.setGeometry(QtCore.QRect(10, 30, 161, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        self.filesAvailable.setFont(font)
        self.filesAvailable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.filesAvailable.setObjectName(_fromUtf8("filesAvailable"))
        self.timeStart = QtGui.QLabel(BeaconView)
        self.timeStart.setGeometry(QtCore.QRect(140, 550, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.timeStart.setFont(font)
        self.timeStart.setText(_fromUtf8(""))
        self.timeStart.setObjectName(_fromUtf8("timeStart"))
        self.checkBoxCompare = QtGui.QCheckBox(BeaconView)
        self.checkBoxCompare.setGeometry(QtCore.QRect(110, 320, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBoxCompare.setFont(font)
        self.checkBoxCompare.setObjectName(_fromUtf8("checkBoxCompare"))
        self.mergeButton = QtGui.QPushButton(BeaconView)
        self.mergeButton.setGeometry(QtCore.QRect(110, 190, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mergeButton.setFont(font)
        self.mergeButton.setObjectName(_fromUtf8("mergeButton"))
        self.plotHistView_4 = GraphicsLayoutWidget(BeaconView)
        self.plotHistView_4.setGeometry(QtCore.QRect(250, 410, 551, 131))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.plotHistView_4.setBackgroundBrush(brush)
        self.plotHistView_4.setObjectName(_fromUtf8("plotHistView_4"))
        self.plotHistView_2 = GraphicsLayoutWidget(BeaconView)
        self.plotHistView_2.setGeometry(QtCore.QRect(250, 150, 551, 131))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.plotHistView_2.setBackgroundBrush(brush)
        self.plotHistView_2.setObjectName(_fromUtf8("plotHistView_2"))
        self.histResetButton_4 = QtGui.QPushButton(BeaconView)
        self.histResetButton_4.setGeometry(QtCore.QRect(190, 430, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histResetButton_4.setFont(font)
        self.histResetButton_4.setObjectName(_fromUtf8("histResetButton_4"))
        self.plotHistView = GraphicsLayoutWidget(BeaconView)
        self.plotHistView.setGeometry(QtCore.QRect(250, 20, 551, 131))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.plotHistView.setBackgroundBrush(brush)
        self.plotHistView.setObjectName(_fromUtf8("plotHistView"))
        self.histogramButton_4 = QtGui.QPushButton(BeaconView)
        self.histogramButton_4.setGeometry(QtCore.QRect(190, 410, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histogramButton_4.setFont(font)
        self.histogramButton_4.setObjectName(_fromUtf8("histogramButton_4"))
        self.histogramButton_2 = QtGui.QPushButton(BeaconView)
        self.histogramButton_2.setGeometry(QtCore.QRect(190, 150, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histogramButton_2.setFont(font)
        self.histogramButton_2.setObjectName(_fromUtf8("histogramButton_2"))
        self.histResetButton_2 = QtGui.QPushButton(BeaconView)
        self.histResetButton_2.setGeometry(QtCore.QRect(190, 170, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histResetButton_2.setFont(font)
        self.histResetButton_2.setObjectName(_fromUtf8("histResetButton_2"))
        self.histogramButton = QtGui.QPushButton(BeaconView)
        self.histogramButton.setGeometry(QtCore.QRect(190, 20, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histogramButton.setFont(font)
        self.histogramButton.setObjectName(_fromUtf8("histogramButton"))
        self.histogramButton_3 = QtGui.QPushButton(BeaconView)
        self.histogramButton_3.setGeometry(QtCore.QRect(190, 280, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histogramButton_3.setFont(font)
        self.histogramButton_3.setObjectName(_fromUtf8("histogramButton_3"))
        self.histResetButton_3 = QtGui.QPushButton(BeaconView)
        self.histResetButton_3.setGeometry(QtCore.QRect(190, 300, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histResetButton_3.setFont(font)
        self.histResetButton_3.setObjectName(_fromUtf8("histResetButton_3"))
        self.plotHistView_3 = GraphicsLayoutWidget(BeaconView)
        self.plotHistView_3.setGeometry(QtCore.QRect(250, 280, 551, 131))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.plotHistView_3.setBackgroundBrush(brush)
        self.plotHistView_3.setObjectName(_fromUtf8("plotHistView_3"))
        self.histResetButton = QtGui.QPushButton(BeaconView)
        self.histResetButton.setGeometry(QtCore.QRect(190, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histResetButton.setFont(font)
        self.histResetButton.setObjectName(_fromUtf8("histResetButton"))

        self.retranslateUi(BeaconView)
        QtCore.QMetaObject.connectSlotsByName(BeaconView)

    def retranslateUi(self, BeaconView):
        BeaconView.setWindowTitle(_translate("BeaconView", "Beacon Viewer", None))
        self.loadImageButton.setText(_translate("BeaconView", "Load", None))
        self.noImageLabel.setText(_translate("BeaconView", "No Image Loaded", None))
        self.readDataButton.setText(_translate("BeaconView", "Add Files", None))
        self.selectAllButton.setText(_translate("BeaconView", "All", None))
        self.selectNoneButton.setText(_translate("BeaconView", "None", None))
        self.loadBeaconsButton.setText(_translate("BeaconView", "Load", None))
        self.clearBeaconsButton.setText(_translate("BeaconView", "Clear", None))
        self.resetImageButton.setText(_translate("BeaconView", "Clear", None))
        self.clearPointsButton.setText(_translate("BeaconView", "Clear", None))
        self.plotResetButton.setText(_translate("BeaconView", "Reset", None))
        self.resetDataButton.setText(_translate("BeaconView", "Reset", None))
        self.timeSeriesButton.setText(_translate("BeaconView", "Plot", None))
        self.putPointsButton.setText(_translate("BeaconView", "Put", None))
        self.label.setText(_translate("BeaconView", "Image", None))
        self.label_2.setText(_translate("BeaconView", "Beacons", None))
        self.label_3.setText(_translate("BeaconView", "Data Points", None))
        self.checkBoxCompare.setText(_translate("BeaconView", "Com", None))
        self.mergeButton.setText(_translate("BeaconView", "Merge All", None))
        self.histResetButton_4.setText(_translate("BeaconView", "Reset", None))
        self.histogramButton_4.setText(_translate("BeaconView", "Plot", None))
        self.histogramButton_2.setText(_translate("BeaconView", "Plot", None))
        self.histResetButton_2.setText(_translate("BeaconView", "Reset", None))
        self.histogramButton.setText(_translate("BeaconView", "Plot", None))
        self.histogramButton_3.setText(_translate("BeaconView", "Plot", None))
        self.histResetButton_3.setText(_translate("BeaconView", "Reset", None))
        self.histResetButton.setText(_translate("BeaconView", "Reset", None))

from pyqtgraph import GraphicsLayoutWidget
